draft
csfloat/extension pull request #177
Opened 2023-08-11 19:09 UTC by ayoung19

2023-08-13 00:02 UTC, Step7750 requested changes
This is super cool! Thank you @ayoung19.

Few minor comments.

2023-08-13 00:05 UTC, ayoung19 commented on .github/workflows/release.yml
> +          npm run build_ff
great idea

2023-08-17 02:20 UTC, Step7750 approved these changes
Awesome stuff, thanks @ayoung19 !

2023-08-17 02:20 UTC, Step7750 commented on .github/workflows/release.yml
> +      - uses: "marvinpinto/action-automatic-releases@latest"
Let's hardcode this to use version `@v1.2.1`, we want to make this workflow deterministic when we can.

2023-08-17 02:20 UTC, Step7750 commented on .github/workflows/upgrade.yml
> +        uses: ad-m/github-push-action@master
Similarly hardcode to `@v0.6.0` for determinism.

2023-08-17 10:20 UTC, merged